---
EnableDefaultLinters: true
exclude:
  - "**/vendor/**/*"
  - "**/node_modules/**/*"
linters:
  # Non-default linters
  PartialInstanceVariable:
    enabled: false
  DeprecatedClasses:
    enabled: false
  ErbSafety:
    enabled: false
  Rubocop:
    enabled: false
    rubocop_config:
      inherit_from:
        - .rubocop.yml
  RequireScriptNonce:
    enabled: false
  NoUnusedDisable:
    enabled: true
