---
EnableDefaultLinters: false
exclude:
  - "**/vendor/**/*"
  - "**/node_modules/**/*"
linters:
  AllowedScriptType:
    enabled: true
  ClosingErbTagIndent:
    enabled: true
  CommentSyntax:
    enabled: true
  ExtraNewline:
    enabled: true
  FinalNewline:
    enabled: true
  NoJavascriptTagHelper:
    enabled: true
  ParserErrors:
    enabled: false
  PartialInstanceVariable:
    enabled: false
  RequireInputAutocomplete:
    enabled: false
  RightTrim:
    enabled: false
  SelfClosingTag:
    enabled: true
  SpaceAroundErbTag:
    enabled: false
  SpaceIndentation:
    enabled: false
  SpaceInHtmlTag:
    enabled: false
  TrailingWhitespace:
    enabled: true
  DeprecatedClasses:
    enabled: false
  ErbSafety:
    enabled: false
  Rubocop:
    enabled: false
    rubocop_config:
      inherit_from:
        - .rubocop.yml
  RequireScriptNonce:
    enabled: false
  NoUnusedDisable:
    enabled: true
