---
EnableDefaultLinters: true
exclude:
  - "**/vendor/**/*"
  - "**/node_modules/**/*"
linters:
  # Non-default linters
  PartialInstanceVariable:
    enabled: false
  DeprecatedClasses:
    enabled: true
  ErbSafety:
    enabled: false
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      # Disable unhelpful rules for ERB templates
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      # Temporarily disabled while we fix
      Layout/FirstArgumentIndentation:
        Enabled: false
      Layout/FirstArrayElementIndentation:
        Enabled: false
      Layout/FirstHashElementIndentation:
        Enabled: false
      Layout/IndentationConsistency:
        Enabled: false
      Layout/IndentationWidth:
        Enabled: false
      Layout/MultilineBlockLayout:
        Enabled: false
      Layout/MultilineMethodCallIndentation:
        Enabled: false
      I18n/RailsI18n/DecorateString:
        Enabled: false
      I18n/RailsI18n/DecorateStringFormattingUsingInterpolation:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
      Style/NestedTernaryOperator:
        Enabled: false
  RequireScriptNonce:
    enabled: true
  NoUnusedDisable:
    enabled: true
