RSpec/PendingWithoutReason:
  Enabled: false

# Offense count: 6
RSpec/BeforeAfterAll:
  Exclude:
    - "spec/jobs/library_scan_job_spec.rb"
    - "spec/jobs/model_file_scan_job_spec.rb"
    - "spec/jobs/model_scan_job_spec.rb"
    - "spec/requests/creators_request_spec.rb"
    - "spec/requests/libraries_request_spec.rb"
    - "spec/requests/models_request_spec.rb"

# Offense count: 4
# Configuration parameters: Prefixes, AllowedPatterns.
# Prefixes: when, with, without
RSpec/ContextWording:
  Exclude:
    - "spec/jobs/model_scan_job_spec.rb"
    - "spec/models/model_spec.rb"

# Offense count: 6
# Configuration parameters: CountAsOne.
RSpec/ExampleLength:
  Max: 11

# Offense count: 29
# Configuration parameters: AssignmentOnly.
RSpec/InstanceVariable:
  Exclude:
    - "spec/models/model_spec.rb"
    - "spec/requests/libraries_request_spec.rb"
    - "spec/requests/models_request_spec.rb"

# Offense count: 14
RSpec/MultipleExpectations:
  Max: 5

# Offense count: 4
RSpec/RepeatedExample:
  Exclude:
    - "spec/models/model_spec.rb"

# Offense count: 1
# Configuration parameters: Include.
# Include: db/migrate/*.rb
Rails/CreateTableWithTimestamps:
  Exclude:
    - "db/migrate/20220612220116_create_active_storage_variant_records.active_storage.rb"

# Offense count: 2
Rails/I18nLocaleTexts:
  Exclude:
    - "app/admin/delayed_job.rb"

# Offense count: 1
# Configuration parameters: Include.
# Include: db/migrate/*.rb
Rails/NotNullColumn:
  Exclude:
    - "db/migrate/20220614211256_add_username_to_users.rb"

# Offense count: 4
Rails/OutputSafety:
  Exclude:
    - "app/admin/delayed_job.rb"
    - "app/helpers/application_helper.rb"
    - "config/initializers/field_with_errors.rb"

# Offense count: 1
# Configuration parameters: Include.
# Include: db/**/*.rb
Rails/ReversibleMigration:
  Exclude:
    - "db/migrate/20220106220519_remove_images_table.rb"

# Offense count: 2
# Configuration parameters: ForbiddenMethods, AllowedMethods.
# ForbiddenMethods: decrement!, decrement_counter, increment!, increment_counter, insert, insert!, insert_all, insert_all!, toggle!, touch, touch_all, update_all, update_attribute, update_column, update_columns, update_counters, upsert, upsert_all
Rails/SkipsModelValidations:
  Exclude:
    - "app/admin/delayed_job.rb"
    - "db/migrate/20220612220115_add_service_name_to_active_storage_blobs.active_storage.rb"

# Offense count: 4
# Configuration parameters: Include.
# Include: app/models/**/*.rb
Rails/UniqueValidationWithoutIndex:
  Exclude:
    - "app/models/library.rb"
    - "app/models/model.rb"
    - "app/models/model_file.rb"
    - "app/models/problem.rb"
