require:
  - standard
  - rubocop-rails
  - rubocop-rspec
  - rubocop-i18n
  - rubocop-performance
  - rubocop-factory_bot

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - db/schema.rb
    - bin/*
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - ".git/**/*"

I18n/GetText:
  Enabled: false
I18n/RailsI18n:
  Enabled: true
  Exclude:
    - "spec/**/*"
RSpec/NestedGroups:
  Max: 4
