blank_issues_enabled: true
contact_links:
  - name: Matrix Chat
    url: https://matrix.to/#/#manyfold:one.ems.host
    about: Come and talk to us with problems, ideas, questions, anything!
  - name: Social Media
    url: https://3dp.chat/@manyfold
    about: Talk to us on Mastodon!
