name: Ruby

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libglfw3
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.16.0
      - name: Install yarn packages
        run: yarn install
      - name: Check typescript
        run: yarn typecheck
      - name: Compile assets
        run: bundle exec rails assets:precompile
      - name: Remove data schema so we bootstrap from zero with data migrations
        run: rm db/data_schema.rb
      - name: Set up database with prepare command so we catch any migration explosions
        run: bundle exec rails db:prepare:with_data
        env:
          RAILS_ENV: test
      - name: Run tests
        uses: paambaati/codeclimate-action@v5.0.0
        with:
          coverageCommand: bundle exec rake
        env:
          CC_TEST_REPORTER_ID: f570c8191542a0db2056d5994b06e9d0be35b25bc6897b5e913c1b783b920a0a
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libglfw3
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.16.0
      - name: Install yarn packages
        run: yarn install
      - name: Lint Ruby code
        run: bundle exec rake rubocop
      - name: Lint Typescript code
        run: yarn run lint:ts
