name: Ruby

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: true
    - name: Set up Node
      uses: actions/setup-node@v2.1.4
      with:
        node-version: 14.6.0
    - name: Install yarn packages
      run: yarn install
    - name: Enable caching for stimulus
      run: bundle exec rails dev:cache
    - name: Compile assets
      run: bundle exec rails webpacker:compile
    - name: Run tests
      run: bundle exec rake
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: true
    - name: Set up Node
      uses: actions/setup-node@v2.1.4
      with:
        node-version: 14.6.0
    - name: Install yarn packages
      run: yarn install
    - name: Lint Ruby code
      run: bundle exec standardrb
    - name: Lint JS code
      run: yarn run standard
